// Auto-generated by generate-menus.ts — do not edit manually
// Generated from tools/hubs/*/index.ts + focus hub definition
// Regenerate: cd plugins/hubs-tui && bun run generate-menus

export interface Sub { label: string; description: string }
export interface Hub { name: string; title: string; description: string; subs: Sub[] }

export const HUBS: Hub[] = [
  {
    "name": "scaffold-hub",
    "title": "Scaffold",
    "description": "Project bootstrap and configuration — detect, provision, verify, repair",
    "subs": [
      {
        "label": "config",
        "description": "Create or edit opencode.jsonc, validated against the live schema"
      },
      {
        "label": "detect",
        "description": "Deep stack detection — languages, frameworks, tools, testing, CI"
      },
      {
        "label": "doctor",
        "description": "Diagnose install health — config, state, hook status"
      },
      {
        "label": "map-codebase",
        "description": "Parallel agents map a brownfield codebase before setup"
      },
      {
        "label": "provision",
        "description": "Generate project config, rules, and agents from the stack"
      },
      {
        "label": "recommend",
        "description": "Map the detected stack to recommended global resources"
      },
      {
        "label": "refresh",
        "description": "Re-detect the stack and re-provision, preserving manual edits"
      },
      {
        "label": "reset",
        "description": "Archive state and context, then start from a clean slate"
      },
      {
        "label": "setup",
        "description": "Full 9-phase project setup — detect, provision, document, verify"
      },
      {
        "label": "status",
        "description": "Show current initialization state and checkpoint progress"
      },
      {
        "label": "tag",
        "description": "Audit and repair resource tags used by stack filtering"
      },
      {
        "label": "verify",
        "description": "Validate configuration completeness, file existence, and reference integrity"
      }
    ]
  },
  {
    "name": "resource-hub",
    "title": "Resource",
    "description": "Authoring and discovery of agents, skills, rules, and commands",
    "subs": [
      {
        "label": "config-orchestrator",
        "description": "Hand config orchestration to the config orchestrator"
      },
      {
        "label": "find-agents",
        "description": "Find and vet subagents for this stack from registries"
      },
      {
        "label": "find-rules",
        "description": "Find and vet rules for this stack from registries and templates"
      },
      {
        "label": "find-skills",
        "description": "Find installable skills for this stack — scans registries, vets, ranks"
      },
      {
        "label": "find-tools",
        "description": "Find and vet TypeScript tools for this stack from registries"
      },
      {
        "label": "effort-estimator",
        "description": "Estimate development effort — pass instructions directly to @effort-estimator"
      },
      {
        "label": "prompt-simplifier",
        "description": "Simplify prompt logic — pass instructions directly to @prompt-simplifier"
      },
      {
        "label": "agent",
        "description": "Create a project-specific agent"
      },
      {
        "label": "command",
        "description": "Create a project slash command"
      },
      {
        "label": "rule",
        "description": "Create a project rule (.opencode/rules/)"
      },
      {
        "label": "skill",
        "description": "Create a reusable skill from session knowledge"
      },
      {
        "label": "graph",
        "description": "Per-project entity graph with vector-then-graph retrieval"
      }
    ]
  },
  {
    "name": "memory-hub",
    "title": "Memory",
    "description": "Durable knowledge and session context — harvest, compress, search, journal",
    "subs": [
      {
        "label": "capture",
        "description": "Capture session knowledge, promote insights to project memory and docs"
      },
      {
        "label": "resume",
        "description": "Resume last ideation session"
      },
      {
        "label": "codebase",
        "description": "Generate hierarchical AGENTS.md across the codebase"
      },
      {
        "label": "compare",
        "description": "Compare options via web research, output as a ranked table"
      },
      {
        "label": "compress",
        "description": "Token compression strategies, with measured savings per technique"
      },
      {
        "label": "consume",
        "description": "Ingest a file, directory, or URL into durable context"
      },
      {
        "label": "context",
        "description": "Harvest, extract, organize, and map context files"
      },
      {
        "label": "decompose",
        "description": "Break down a concept or goal into smaller actionable units"
      },
      {
        "label": "diff",
        "description": "Diff current context against a checkpoint — new decisions, patterns"
      },
      {
        "label": "export",
        "description": "Export context as a summary, bundle, or team report"
      },
      {
        "label": "journal",
        "description": "Event-sourced orchestration log — replay and time-travel debug"
      },
      {
        "label": "memory",
        "description": "Promote durable knowledge into project memory, notepad, or wiki"
      },
      {
        "label": "prune",
        "description": "Archive or delete superseded context to keep the store healthy"
      },
      {
        "label": "search",
        "description": "Semantic search across context — decisions, patterns, research"
      },
      {
        "label": "secondbrain",
        "description": "Local-first knowledge base in markdown, versioned by git"
      },
      {
        "label": "session",
        "description": "Extract decisions and learnings from the current session"
      },
      {
        "label": "sweep",
        "description": "Find files in .opencode/ that should be gitignored"
      },
      {
        "label": "web-research",
        "description": "Parallel multi-query web research, synthesized into a saved report"
      }
    ]
  },
  {
    "name": "research-hub",
    "title": "Research",
    "description": "Investigation and discovery — web, competitive, tech-eval, codebase analysis",
    "subs": [
      {
        "label": "convention-extractor",
        "description": "Extract coding conventions — pass instructions directly to @convention-extractor"
      },
      {
        "label": "analyst",
        "description": "Strategic analyst — pass instructions directly to @analyst"
      },
      {
        "label": "analyze-patterns",
        "description": "Analyze code patterns and anti-patterns — consistencies, convention violations"
      },
      {
        "label": "competitive-analysis",
        "description": "Competitive landscape — feature comparison matrix"
      },
      {
        "label": "graph",
        "description": "Visual relationship mapping — dependencies, components, tradeoffs"
      },
      {
        "label": "research",
        "description": "Multi-model synthesis — diverse perspectives merged into one answer"
      },
      {
        "label": "tech-eval",
        "description": "Technology evaluation — structured pros/cons comparison against alternatives"
      },
      {
        "label": "web-research",
        "description": "Multi-source web research — parallel searches, synthesize findings"
      },
      {
        "label": "scientist",
        "description": "Data analysis specialist — pass instructions directly to @scientist"
      },
      {
        "label": "tracer",
        "description": "Evidence-driven causal tracing — pass instructions directly to @tracer"
      },
      {
        "label": "docs",
        "description": "Official library docs via Context7 — React, Next, Tailwind, any"
      },
      {
        "label": "document-specialist",
        "description": "Hand external docs lookups to the document specialist"
      },
      {
        "label": "explore",
        "description": "Codebase search specialist — pass instructions directly to @explore"
      }
    ]
  },
  {
    "name": "design-hub",
    "title": "Design",
    "description": "Architecture, design, and documentation authoring",
    "subs": [
      {
        "label": "docs",
        "description": "Generate hierarchical AGENTS.md documentation across the codebase"
      },
      {
        "label": "arch-prep",
        "description": "Architecture prep for upcoming features — extension points, refactoring runway"
      },
      {
        "label": "architecture",
        "description": "Architectural friction analysis — propose deep-module refactors"
      },
      {
        "label": "modularity",
        "description": "Module boundary analysis — detect circular dependencies, suggest reorg"
      },
      {
        "label": "redesign",
        "description": "Audit and upgrade existing UI to premium design standards"
      },
      {
        "label": "designer",
        "description": "UI/UX designer-developer — pass instructions directly to @designer"
      },
      {
        "label": "frontend-design",
        "description": "Hand production frontend work to the frontend designer"
      },
      {
        "label": "readme",
        "description": "Rewrite README to match the current codebase, keeping its tone"
      },
      {
        "label": "writer",
        "description": "Technical documentation writer — pass instructions directly to @writer"
      }
    ]
  },
  {
    "name": "ideate-hub",
    "title": "Ideate",
    "description": "Divergent thinking and idea generation",
    "subs": [
      {
        "label": "adversarial-debate",
        "description": "Spec validation via oppositional debate — proposer vs critics"
      },
      {
        "label": "brainstorm",
        "description": "Free-form idea generation — diverge then converge"
      },
      {
        "label": "cleanroom",
        "description": "Formal correctness — box structure decomposition and statistical testing"
      },
      {
        "label": "ddd",
        "description": "Domain-driven design — model bounded contexts, aggregates, domain events"
      },
      {
        "label": "deep",
        "description": "Socratic interview with ambiguity gating — crystallize vague requirements"
      },
      {
        "label": "deep-dive",
        "description": "Trace the root cause, then crystallize the requirements"
      },
      {
        "label": "deep-thinker",
        "description": "Structured thinking partner — pass instructions directly to @deep-thinker"
      },
      {
        "label": "double-diamond",
        "description": "Design Council framework — discover, define, develop, deliver"
      },
      {
        "label": "event-storming",
        "description": "Collaborative domain exploration via timeline, commands, events, policies"
      },
      {
        "label": "grill",
        "description": "Stress-test a plan with relentless one-at-a-time questioning"
      },
      {
        "label": "opro",
        "description": "⚠️ EXPENSIVE: Optimize prompts by testing variations against benchmarks"
      },
      {
        "label": "pwf",
        "description": "Filesystem-as-disk planning — quality-gated convergence with recovery"
      },
      {
        "label": "refine",
        "description": "Diverge/converge iteration — expand ideas, then sharpen them"
      },
      {
        "label": "rpikit",
        "description": "Research-Plan-Implement — stakes-based rigor scaling"
      },
      {
        "label": "spark",
        "description": "Project-aware idea prompts, short and expandable"
      },
      {
        "label": "tree-of-thoughts",
        "description": "⚠️ EXPENSIVE: Explore parallel solution branches for open-ended problems"
      }
    ]
  },
  {
    "name": "plan-hub",
    "title": "Plan",
    "description": "Requirements, roadmaps, and work decomposition",
    "subs": [
      {
        "label": "bottom-up",
        "description": "Build up from existing primitives and capabilities into composed systems"
      },
      {
        "label": "constitution",
        "description": "Project governance — code, UX, performance, security principles"
      },
      {
        "label": "decomposition",
        "description": "Break complex work into ordered, verifiable subtasks"
      },
      {
        "label": "impact-mapping",
        "description": "Goal mapping — trace deliverables to business impact"
      },
      {
        "label": "improvements",
        "description": "Audit the project for major and minor improvements, ranked"
      },
      {
        "label": "jtbd",
        "description": "Jobs-to-be-done — frame requirements around customer functional jobs"
      },
      {
        "label": "lean-canvas",
        "description": "Lean business model — problem, solution, metrics, competitive advantage"
      },
      {
        "label": "plan",
        "description": "Interview-style strategic planning — clarify goals, break into tasks"
      },
      {
        "label": "quality",
        "description": "Code quality audit — complexity, duplication, naming, error handling"
      },
      {
        "label": "ralplan",
        "description": "Consensus planning gate — validate plan is concrete enough to execute"
      },
      {
        "label": "requirements-analyzer",
        "description": "Hand feature requirements analysis to the specialist"
      },
      {
        "label": "spiral",
        "description": "Risk-driven iterative planning — each cycle targets highest-risk items first"
      },
      {
        "label": "status",
        "description": "Show current ideation state"
      },
      {
        "label": "story-mapping",
        "description": "User story mapping — journey spine with release prioritization"
      },
      {
        "label": "top-down",
        "description": "Decompose from high-level vision into components and sub-systems"
      },
      {
        "label": "plan-execute",
        "description": "Architect plans the whole thing, executor builds it stepwise"
      }
    ]
  },
  {
    "name": "verify-hub",
    "title": "Verify",
    "description": "Review, test, and debug — proving the work is correct",
    "subs": [
      {
        "label": "critic",
        "description": "Work plan and code review expert — pass instructions directly to @critic"
      },
      {
        "label": "security-reviewer",
        "description": "Hand a security audit to the security reviewer"
      },
      {
        "label": "tdd",
        "description": "Red-green-refactor loop until every feature has a test"
      },
      {
        "label": "audit",
        "description": "One-command health check — deps, security, quality, tests, size"
      },
      {
        "label": "code-review",
        "description": "Delegated code review — pass instructions directly to @code-reviewer"
      },
      {
        "label": "create-tests",
        "description": "Generate comprehensive 8-type test suite"
      },
      {
        "label": "debugger",
        "description": "Root-cause analysis — pass instructions directly to @debugger"
      },
      {
        "label": "deep-bug-hunt",
        "description": "Critical bug hunt on recent changes — regressions, data loss, security holes"
      },
      {
        "label": "qa-tester",
        "description": "Interactive CLI testing specialist — pass instructions directly to @qa-tester"
      },
      {
        "label": "review",
        "description": "Full review round — changes, security scan, complexity"
      },
      {
        "label": "test-engineer",
        "description": "Test strategy specialist — pass instructions directly to @test-engineer"
      }
    ]
  },
  {
    "name": "swarm-hub",
    "title": "Swarm",
    "description": "Multi-agent topologies and swarm patterns",
    "subs": [
      {
        "label": "hive-plan",
        "description": "Agent swarm planning — interview, discover, produce plan.md with approval gate"
      },
      {
        "label": "cc10x",
        "description": "Route intent to build, debug, review, or plan with confidence gating"
      },
      {
        "label": "devin",
        "description": "Autonomous plan → code → debug → deploy with root-cause loops"
      },
      {
        "label": "gastown",
        "description": "If the work is on your hook, you run it — git-backed work units"
      },
      {
        "label": "gsd",
        "description": "Discuss → plan → execute → verify → ship, one fresh context per task"
      },
      {
        "label": "harden",
        "description": "Composable robustness — safe task, circuit breaker, verification gate"
      },
      {
        "label": "hive",
        "description": "Batched parallel workers with worktree isolation and blocked-worker protocol"
      },
      {
        "label": "maestro",
        "description": "Strict roles — PMs gather, architects design, coders implement"
      },
      {
        "label": "metaswarm",
        "description": "Autonomous issue-to-PR, 7 phases, adversarial fresh reviews"
      },
      {
        "label": "pair",
        "description": "Two agents on one task — a driver writes, a navigator reviews live"
      },
      {
        "label": "react",
        "description": "ReAct loop — think, act, observe, reason, repeat until done"
      },
      {
        "label": "remediate",
        "description": "Watch CI, diagnose the cause, fix, re-run until green"
      },
      {
        "label": "ruflo",
        "description": "60+ agent swarm with Q-learning routing and 4 consensus protocols"
      },
      {
        "label": "self-assess",
        "description": "Iterate: execute, critique against thresholds, refine, repeat"
      },
      {
        "label": "spec-driven",
        "description": "Spec-first development — formalize spec, validate it, then implement against it"
      },
      {
        "label": "subagent-driven",
        "description": "One fresh subagent per task, with review gates after each"
      },
      {
        "label": "delegate",
        "description": "Hand a bounded task to a separate CLI session, then review its diff"
      }
    ]
  },
  {
    "name": "build-hub",
    "title": "Build",
    "description": "Implementation, refactoring, and code transformation",
    "subs": [
      {
        "label": "overhaul",
        "description": "8-dimension project audit — produce prioritized improvement plan"
      },
      {
        "label": "brownfield",
        "description": "Add a feature to existing code — find the seams, then implement"
      },
      {
        "label": "pipeline",
        "description": "Declarative stages: lint → test → build → deploy, each gating the next"
      },
      {
        "label": "vibe-code",
        "description": "Describe an app in prose, get full-stack code, iterate conversationally"
      },
      {
        "label": "cleanup",
        "description": "Remove AI slop — dead code, redundant comments, unused exports"
      },
      {
        "label": "executor",
        "description": "Focused task executor — pass instructions directly to @executor"
      },
      {
        "label": "extract-standards",
        "description": "Infer a style guide from the code that already exists"
      },
      {
        "label": "modernize",
        "description": "Modernize patterns in place, preserving behavior"
      },
      {
        "label": "optimize",
        "description": "Analyze code for performance and security issues, then apply targeted fixes"
      },
      {
        "label": "refactor",
        "description": "Restructure without changing behavior — extract, split, decouple"
      },
      {
        "label": "simplify",
        "description": "Reduce complexity — flatten nesting, simplify conditionals"
      },
      {
        "label": "simplify-code",
        "description": "Simplify for clarity — behavior preserved, scope respected"
      }
    ]
  },
  {
    "name": "orchestrate-hub",
    "title": "Orchestrate",
    "description": "Autonomous execution modes and orchestration loops",
    "subs": [
      {
        "label": "autopilot",
        "description": "Full autonomous execution from idea to working code"
      },
      {
        "label": "ccg",
        "description": "Multi-model synthesis — query diverse models, merge perspectives"
      },
      {
        "label": "consensus",
        "description": "Run agents independently, then resolve by vote or synthesis"
      },
      {
        "label": "evolutionary",
        "description": "Ship incrementally, validating fitness each generation"
      },
      {
        "label": "ralph",
        "description": "Persistent loop — keeps working until task is verified complete"
      },
      {
        "label": "resume",
        "description": "Resume last orchestration session"
      },
      {
        "label": "sciomc",
        "description": "Parallel scientist agents for comprehensive analysis"
      },
      {
        "label": "state-machine",
        "description": "Agents as states, with explicit transitions and guards"
      },
      {
        "label": "status",
        "description": "Show current orchestration state"
      },
      {
        "label": "swarm",
        "description": "Architect-led team of 11 specialized agents with gated QA pipeline"
      },
      {
        "label": "team",
        "description": "N coordinated agents with shared task list and real-time messaging"
      },
      {
        "label": "ultrawork",
        "description": "Maximum parallel execution for high-throughput tasks"
      }
    ]
  },
  {
    "name": "git-hub",
    "title": "Git",
    "description": "Version control, pull requests, and releases",
    "subs": [
      {
        "label": "archive",
        "description": "Move stale branches and artifacts to a timestamped archive"
      },
      {
        "label": "changelog",
        "description": "Generate user-facing changelog from git commits"
      },
      {
        "label": "commit",
        "description": "Create well-formatted conventional commit"
      },
      {
        "label": "commit-drafter",
        "description": "Hand commit message drafting to the commit drafter"
      },
      {
        "label": "gh",
        "description": "Full GitHub CLI operations via gh"
      },
      {
        "label": "git-cleanup",
        "description": "Drop CHANGELOG entries whose commits are no longer in history"
      },
      {
        "label": "git-master",
        "description": "Git expert for atomic commits — pass instructions directly to @git-master"
      },
      {
        "label": "git-stage-thread",
        "description": "Stage git changes from current conversation thread"
      },
      {
        "label": "pr",
        "description": "Create, view, merge, or manage pull requests"
      },
      {
        "label": "release",
        "description": "Bump the version, changelog, and GitHub release in one flow"
      }
    ]
  },
  {
    "name": "maintain-hub",
    "title": "Maintain",
    "description": "Project hygiene, insights, and self-improvement",
    "subs": [
      {
        "label": "consolidate-telemetry",
        "description": "Consolidate SRCL telemetry log into proposed ADRs in decisions.md"
      },
      {
        "label": "converge",
        "description": "Five-gate quality convergence with escalating targets"
      },
      {
        "label": "icon",
        "description": "Generate web/PWA/UE icon assets from source image"
      },
      {
        "label": "insights",
        "description": "Analyze session history — patterns, friction, recommendations"
      },
      {
        "label": "organize",
        "description": "Find duplicates, suggest structures, automate cleanup"
      },
      {
        "label": "purge",
        "description": "Remove stale runs to free space, keeping recent history"
      },
      {
        "label": "retrospect",
        "description": "Post-run retrospective — lessons, error taxonomy, metrics"
      },
      {
        "label": "sandbox",
        "description": "Policy-based tool control — file, command, and network limits"
      },
      {
        "label": "scan",
        "description": "Security scan — SAST, secrets, dependencies, compliance"
      },
      {
        "label": "self-improve",
        "description": "Capture learnings and promote recurring fixes into config"
      },
      {
        "label": "vectorize",
        "description": "Embed codebase + context into local vector DB for semantic retrieval"
      },
      {
        "label": "workspace",
        "description": "Manage .opencode across projects — init, sync, health"
      }
    ]
  },
  {
    "name": "skills-hub",
    "title": "Skills",
    "description": "Skill authoring and lifecycle management",
    "subs": [
      {
        "label": "add",
        "description": "Wizard that writes a new SKILL.md from prompted answers"
      },
      {
        "label": "create",
        "description": "Create a skill end to end, including scripts and references"
      },
      {
        "label": "edit",
        "description": "Interactively edit a skill's description, triggers, or content"
      },
      {
        "label": "info",
        "description": "Show a skill's full frontmatter and content"
      },
      {
        "label": "list",
        "description": "List every skill by scope with quality and usage stats"
      },
      {
        "label": "package",
        "description": "Validate a skill, then build a distributable archive"
      },
      {
        "label": "remove",
        "description": "Remove a skill by name after confirming"
      },
      {
        "label": "scan",
        "description": "Fast non-interactive inventory of user and project skill scopes"
      },
      {
        "label": "search",
        "description": "Search skills by name, description, or content across all scopes"
      },
      {
        "label": "setup",
        "description": "Wizard — create skill dirs, scan inventory, choose actions"
      },
      {
        "label": "sync",
        "description": "Sync skills between user and project scope, showing the diff"
      },
      {
        "label": "update",
        "description": "Iterate an existing skill through the skill-creator workflow"
      },
      {
        "label": "validate",
        "description": "Check a skill's structure and report what to fix"
      }
    ]
  },
  {
    "name": "focus",
    "title": "Focus",
    "description": "Manage session focus and goals",
    "subs": [
      {
        "label": "set",
        "description": "Set or update session focus objective with optional success criteria and constraints"
      },
      {
        "label": "show",
        "description": "Display current focus status — objective, progress, budget"
      },
      {
        "label": "clear",
        "description": "Clear/remove current focus and stop auto-continue"
      },
      {
        "label": "pause",
        "description": "Pause focus without clearing — preserve state for later resume"
      },
      {
        "label": "resume",
        "description": "Resume a paused or stopped focus session"
      }
    ]
  }
]
