import { tool } from "@opencode-ai/plugin"
import { HUBS, getDelegation } from "./hubMenu"
import * as fs from "fs"

function generateRoutingDocs(): string {
  const lines: string[] = [
    "# Hub Routing (Auto-generated from hubMenu.ts)",
    "",
    "> This file is auto-generated by `tools/gen-routing-docs.ts`. Do not edit manually.",
    "> Run `npx tsx tools/gen-routing-docs.ts` to regenerate.",
    "",
    "| Hub | Subcommand | Delegation | Target |",
    "|-----|-----------|------------|--------|"
  ]

  for (const hub of HUBS) {
    for (const sub of hub.subcommands) {
      const { type, target } = getDelegation(sub)
      const targetStr = target || (type === 'inline' ? '—' : '—')
      lines.push(`| ${hub.name} | ${sub.label} | ${type} | ${targetStr} |`)
    }
  }

  lines.push("")
  return lines.join("\n")
}

export default tool({
  description: "Generate hub routing documentation from canonical hubMenu.ts data",
  args: {
    output: tool.schema.string().optional().describe("Output file path (defaults to stdout)")
  },
  async execute(args) {
    const markdown = generateRoutingDocs()

    if (args.output) {
      fs.writeFileSync(args.output, markdown, "utf-8")
      return JSON.stringify({ generated: true, outputPath: args.output, size: markdown.length })
    }

    // Output to stdout
    console.log(markdown)
    return JSON.stringify({ generated: true, outputPath: "stdout", size: markdown.length })
  }
})
