// Generate TUI hub menus from canonical hub manifests
// Run: bun run generate-menus (from plugins/hubs-tui/)
// This eliminates drift between the TUI plugin and the hub manifests.

import { writeFileSync } from "fs"
import { join, dirname } from "path"
import { fileURLToPath } from "url"

import scaffoldHub from "../../tools/hub-scaffold-hub"
import resourceHub from "../../tools/hub-resource-hub"
import memoryHub from "../../tools/hub-memory-hub"
import researchHub from "../../tools/hub-research-hub"
import designHub from "../../tools/hub-design-hub"
import ideateHub from "../../tools/hub-ideate-hub"
import planHub from "../../tools/hub-plan-hub"
import verifyHub from "../../tools/hub-verify-hub"
import swarmHub from "../../tools/hub-swarm-hub"
import buildHub from "../../tools/hub-build-hub"
import orchestrateHub from "../../tools/hub-orchestrate-hub"
import gitHub from "../../tools/hub-git-hub"
import maintainHub from "../../tools/hub-maintain-hub"
import skillsHub from "../../tools/hub-skills-hub"

const __dirname = dirname(fileURLToPath(import.meta.url))

interface Sub { label: string; description: string }
interface Hub { name: string; title: string; description: string; subs: Sub[] }

function titleFromName(name: string): string {
  // Most hubs derive title from name (kebab -> Title Case)
  // Some have custom titles
  const custom: Record<string, string> = {
    "project": "Project Ops",
  }
  if (custom[name]) return custom[name]
  return name.replace(/-hub$/, "").split("-").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ")
}

const hubs: Hub[] = [
  scaffoldHub,
  resourceHub,
  memoryHub,
  researchHub,
  designHub,
  ideateHub,
  planHub,
  verifyHub,
  swarmHub,
  buildHub,
  orchestrateHub,
  gitHub,
  maintainHub,
  skillsHub,].map((h) => ({
  name: h.name,
  title: titleFromName(h.name),
  description: h.description,
  subs: h.subcommands.map((s) => ({ label: s.label, description: s.description })),
}))

// Focus hub (TUI-only — not exposed as a tools/ hub manifest)
hubs.push({
  name: "focus",
  title: "Focus",
  description: "Manage session focus and goals",
  subs: [
    { label: "set", description: "Set or update session focus objective with optional success criteria and constraints" },
    { label: "show", description: "Display current focus status — objective, progress, budget" },
    { label: "clear", description: "Clear/remove current focus and stop auto-continue" },
    { label: "pause", description: "Pause focus without clearing — preserve state for later resume" },
    { label: "resume", description: "Resume a paused or stopped focus session" },
  ],
})

const totalSubs = hubs.reduce((a, h) => a + h.subs.length, 0)

const output = `// Auto-generated by generate-menus.ts — do not edit manually
// Generated from tools/hubs/*/index.ts + focus hub definition
// Regenerate: cd plugins/hubs-tui && bun run generate-menus

export interface Sub { label: string; description: string }
export interface Hub { name: string; title: string; description: string; subs: Sub[] }

export const HUBS: Hub[] = ${JSON.stringify(hubs, null, 2)}
`

const outputPath = join(__dirname, "src", "generated-hubs.ts")
writeFileSync(outputPath, output, "utf-8")
console.log(`Generated ${outputPath}`)
console.log(`  ${hubs.length} hubs, ${totalSubs} subcommands`)
