// Generate TUI hub menus from canonical hub manifests
// Run: bun run generate-menus (from plugins/hubs-tui/)
// This eliminates drift between the TUI plugin and the hub manifests.

import { writeFileSync } from "fs"
import { join, dirname } from "path"
import { fileURLToPath } from "url"

import initProjectHub from "../../tools/hub-init-project"
import ideationHub from "../../tools/hub-ideation"
import orchestrateHub from "../../tools/hub-orchestrate"
import harvestContextHub from "../../tools/hub-harvest-context"
import projectHub from "../../tools/hub-project"
import skillsHub from "../../tools/hub-skills"

const __dirname = dirname(fileURLToPath(import.meta.url))

interface Sub { label: string; description: string }
interface Hub { name: string; title: string; description: string; subs: Sub[] }

function titleFromName(name: string): string {
  // Most hubs derive title from name (kebab -> Title Case)
  // Some have custom titles
  const custom: Record<string, string> = {
    "project": "Project Ops",
  }
  if (custom[name]) return custom[name]
  return name.split("-").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ")
}

const hubs: Hub[] = [
  initProjectHub,
  ideationHub,
  orchestrateHub,
  harvestContextHub,
  projectHub,
  skillsHub,
].map((h) => ({
  name: h.name,
  title: titleFromName(h.name),
  description: h.description,
  subs: h.subcommands.map((s) => ({ label: s.label, description: s.description })),
}))

// Focus hub (TUI-only — not exposed as a tools/ hub manifest)
hubs.push({
  name: "focus",
  title: "Focus",
  description: "Manage session focus and goals",
  subs: [
    { label: "set", description: "Set or update session focus objective with optional success criteria and constraints" },
    { label: "show", description: "Display current focus status — objective, progress, budget" },
    { label: "clear", description: "Clear/remove current focus and stop auto-continue" },
    { label: "pause", description: "Pause focus without clearing — preserve state for later resume" },
    { label: "resume", description: "Resume a paused or stopped focus session" },
  ],
})

const totalSubs = hubs.reduce((a, h) => a + h.subs.length, 0)

const output = `// Auto-generated by generate-menus.ts — do not edit manually
// Generated from tools/hubs/*/index.ts + focus hub definition
// Regenerate: cd plugins/hubs-tui && bun run generate-menus

export interface Sub { label: string; description: string }
export interface Hub { name: string; title: string; description: string; subs: Sub[] }

export const HUBS: Hub[] = ${JSON.stringify(hubs, null, 2)}
`

const outputPath = join(__dirname, "src", "generated-hubs.ts")
writeFileSync(outputPath, output, "utf-8")
console.log(`Generated ${outputPath}`)
console.log(`  ${hubs.length} hubs, ${totalSubs} subcommands`)
